/**
 * CONFIGURACIÓN GLOBAL DE HOJAS Y ESQUEMAS (Source of Truth)
 * 
 * Este archivo centraliza los nombres de las hojas y sus encabezados físicos.
 * Permite que el sistema sea modular y soporte diferentes estructuras entre clientes.
 */

const SHEETS = {
  STORES: "BD_TIENDAS",
  PRODUCTS: "BD_PRODUCTOS",
  PRODUCT_VARIETIES: "BD_VARIEDAD_PRODUCTOS",
  PRODUCT_IMAGES: "BD_PRODUCTO_IMAGENES",
  LAB_IA: "BD_LABORATORIO_IA",
  INVENTORY: "BD_INVENTARIO",
  INVENTORY_MOVEMENTS: "BD_MOVIMIENTOS_INVENTARIO",
  DEPOSIT: "BD_DEPOSITO",
  CATEGORIES: "BD_CATEGORIAS",
  COLORS: "BD_COLORES",
  CLIENTS: "BD_CLIENTES",
  BLOGGER_SALES: "BLOGGER_VENTAS",
  BLOGGER_SALES_DETAILS: "BLOGGER_DETALLE_VENTAS",
  BLOGGER_CONFIG: "BLOGGER_CONFIGURACION",
  VENTAS_PEDIDOS: "BD_VENTAS_PEDIDOS",
  DETALLE_VENTAS: "BD_DETALLE_VENTAS",
  GESTION_CAJA: "BD_GESTION_CAJA",
  METODOS_PAGO: "BD_METODOS_PAGO",
  DATOS_TRANSFERENCIA: "BD_DATOS_TRANSFERENCIA",
  USUARIOS_SISTEMAS: "BD_USUARIOS_SISTEMAS",
  APP_SCRIPT_CONFIG: "BD_APP_SCRIPT",
  GENERAL_CONFIG: "BD_CONFIGURACION_GENERAL",
  SHIPPING_AGENCIES: "BD_AGENCIAS_ENVIO",
  SVG_GALLERY: "BD_GALERIA_SVG",
  WC_ORDERS: "BD_VENTAS_WOOCOMMERCE",
  WC_DETAILS: "BD_DETALLE_VENTAS_WOOCOMMERCE",
  TARIFARIO_GCP: "BD_TARIFARIO_GCP",
  BARTENDER_HISTORY: "BD_BARTENDER_HISTORY",
  CLIENT_FORM_LOG: "BD_CLIENT_FORM_LOG",
  LAB_BATCH_QUEUE: "BD_COLA_BATCH"
};

const SHEET_SCHEMA = {
  LAB_BATCH_QUEUE: ["TIMESTAMP", "BATCH_ID", "MODELO", "IMAGEN_IDS", "ESTADO", "ERROR_DETALLE"],
  PRODUCT_IMAGES: ["IMAGEN_ID", "PRODUCTO_ID", "CARPETA_ID", "IMAGEN_RUTA", "ARCHIVO_ID", "URL", "ESTADO", "FECHA_CARGA", "FUENTE", "PORTADA", "TIPO_ARCHIVO", "PESO_ARCHIVO", "FORMATO_ARCHIVO", "THUMBNAIL_URL", "ORDEN", "SYNC_WC", "ANALISIS_FORENSE"],
  PRODUCTS: ["CODIGO_ID", "CATEGORIA_PADRE", "CATEGORIA", "SKU", "WOO_ID", "CARPETA_ID", "TEMPORADA", "GENERO", "MARCA", "MODELO", "ESTILO", "MATERIAL", "TALLES", "COLORES", "DESCRIPCION_IA", "PRECIO_COSTO", "RECARGO_MENOR", "ID_VIDEO_YOUTUBE", "SINCRONIZAR_FOTOS_VARIACIONES", "BLOGGER_POST_ID", "ESTADO_SINCRONIZACION", "ULTIMA_ACTUALIZACION", "GRUPO_EDAD"],
  CATEGORIES: ["CATEGORIA_GENERAL", "CATEGORIA_ID", "LISTADO_MARCAS", "LISTADO_TALLES", "LISTADO_PRECIOS", "RECARGO_MENOR", "GENERAR_HTML", "HTML", "ICONO"],
  STORES: ["TIENDA_ID", "LOGOTIPO", "SOBRE_NOSOTROS", "INICIO_ACTIVIDADES", "DIRECCION", "HORA_APERTURA", "HORA_CIERRE", "COORDENADAS", "ID_GOOGLE_MAPS", "TELEFONO", "CELULAR", "CORREO_ELECTRONICO", "QR_DATA", "VENDEDOR_ID", "TIPO_COMPROBANTE", "IP_IMPRESORA_LOCAL", "CANTIDAD_COPIAS", "ACTIVAR_SONIDO", "MENSAJE_MARKETING", "MONTO_MINIMO_CUPON", "MODO_VENTA", "METODOS_PAGO", "CUENTAS_TRANSFERENCIA", "COMPRA_MINIMA", "RECARGO_MENOR"],
  INVENTORY: ["INVENTARIO_ID", "FECHA_CREACION", "TIENDA_ID", "PRODUCTO_ID", "COLOR", "TALLE", "STOCK_INICIAL", "ENTRADAS", "SALIDAS", "VENTAS_WEB", "VENTAS_LOCAL", "STOCK_ACTUAL", "FECHA_ACTUALIZACION", "AJUSTE_CANTIDAD"],
  INVENTORY_MOVEMENTS: ["REGISTRO_ID", "USER_ID", "FECHA", "INVENTARIO_ID", "MOVIMIENTO", "ORIGEN", "DESTINO", "PRODUCTO_ID", "CANTIDAD", "REFERENCIA"],
  DEPOSIT: ["PRODUCTO_ID", "STOCK_INICIAL", "ENTRADAS", "SALIDAS", "STOCK_ACTUAL", "FECHA_ACTUALIZACION"],
  COLORS: ["COLOR_ID", "RED", "GREEN", "BLUE", "TEXTO", "BORDE", "COMBINACION", "HEXADECIMAL", "IMAGEN"],
  GENERAL_CONFIG: ["GENERAL_ID", "RESPONSABLE", "CUIT", "TELEFONO", "CELULAR", "CORREO_ELECTRONICO", "TIENDA_BLOGGER", "SITIO_WEB", "CATALOGO_DRIVE", "FORMULARIO_COMPROBANTE", "FORMULARIO_CLIENTE", "FACEBOOK", "INSTAGRAM", "TIKTOK", "TIPO_REGISTRO_PRODUCTO", "TIPO_REGISTRO_PRECIO", "EXCLUIR_SURTIDOS_VARIANTES", "DOLAR_BLUE_VENTA", "DOLAR_BLUE_COMPRA", "CLAVE_FILESTACK", "SIN_IMAGEN", "LIMITE_IMAGENES_PRODUCTO", "APLICAR_MARCA_DE_AGUA", "HORA_DISPARADOR_BARTENDER", "CARRUSELES"],
  SHIPPING_AGENCIES: ["AGENCIA_ID", "COSTO_ENVIO", "HORA_ENTREGA", "CUIT", "UBICACION", "ESTADO"],
  PRODUCT_VARIETIES: ["VARIEDAD_ID", "CATEGORIA", "PRODUCTO_ID", "VARIEDAD", "PRECIO_UNITARIO", "CANTIDAD_MINIMA", "VISIBILIDAD_TIENDA", "ULTIMA_ACTUALIZACION"],
  SVG_GALLERY: ["SVG_ID", "NOMBRE", "TIPO", "SVG_CODE", "PERSONALIZAR", "COLOR_CIRCULO", "TAMAÑO_CIRCULO", "X_CIRCULO", "C_TEXTO", "Y_CIRCULO", "COLOR_TEXTO"],
  BLOGGER_SALES: ["CODIGO", "FECHA", "HORA", "CAJA_ID", "METODO_PAGO", "DATOS_TRANSFERENCIA", "CLIENTE_ID", "CELULAR", "AGENCIA", "TIEMPO_ENTREGA_AGENCIA", "MONEDA", "COSTO_ENVIO", "RECARGO_TRANSFERENCIA", "TOTAL_VENTA", "DETALLE_JSON", "ESTADO", "JSON_BACKUP", "URL_COMPROBANTE"],
  BLOGGER_SALES_DETAILS: ["VENTA_ID", "PRODUCTO_VARIACION", "DETALLE_JSON", "CANTIDAD", "PRECIO", "SUBTOTAL", "PRODUCTO_ID", "COLOR", "TALLE", "VARIEDAD_ID"],
  BLOGGER_CONFIG: ["PARAMETRO_ID", "CONFIGURACION", "TIENDA_ID"],
  CLIENTS: ["CLIENTE_ID", "CLASIFICACION", "NOMBRE_COMPLETO", "CELULAR", "CORREO_ELECTRONICO", "CUIT_DNI", "CONDICION_FISCAL", "TIPO_ENVIO", "AGENCIA_ENVIO", "CODIGO_POSTAL", "PROVINCIA", "MUNICIPIO", "LOCALIDAD", "CALLE", "NUMERO", "PISO", "DEPARTAMENTO", "OBSERVACION"],
  VENTAS_PEDIDOS: ["VENTA_ID", "TIENDA_ID", "ASESOR_ID", "FECHA", "HORA", "CLIENTE_ID", "CAJA_ID", "TIPO_VENTA", "COMPRA_MINIMA", "PAGO_MIXTO", "METODO_PAGO", "DATOS_TRANSFERENCIA", "DESACTIVAR_RECARGO_TRANSFERENCIA", "MONTO_TOTAL_PRODUCTOS", "PAGO_EFECTIVO", "SUBTOTAL", "RECARGO_MENOR", "COSTO_ENVIO", "RECARGO_TRANSFERENCIA", "TOTAL_VENTA", "ESTADO", "CAMBIOS", "COMPROBANTE_FILE", "DETALLE_AUDITORIA_IA", "DETALLE_JSON"],
  DETALLE_VENTAS: ["VENTA_ID", "REGISTRO_ID", "SCAN", "VARIACION_ID", "CATEGORIA_PADRE", "CATEGORIA", "TEMPORADA", "PRODUCTO_ID", "COLOR", "TALLE", "TIPO_PRECIO", "PRECIO", "CANTIDAD", "MONTO", "INVERSION", "GANANCIA", "DESCRIPCION_VENTA"],
  GESTION_CAJA: ["CAJA_ID", "TIENDA_ID", "ASESOR_ID", "FECHA", "CUENTA_TRANSFERENCIA", "HORA_INICIADA", "HORA_FINALIZADA", "ESTADO"],
  METODOS_PAGO: ["MOVIMIENTO_ID", "PORCENTAJE", "TERMINOS_CONDICIONES", "ICONO"],
  DATOS_TRANSFERENCIA: ["CUENTA_ID", "COLOR", "TIPO_CUENTA", "BANCO", "NOMBRE_CUENTA", "ALIAS", "CBU", "ESTADO"],
  USUARIOS_SISTEMAS: ["USER_ID", "NOMBRE", "ESTADO"],
  APP_SCRIPT_CONFIG: ["MACRO_ID", "GRUPO", "TIPO_CLAVE", "VALOR", "DESCRIPCION"],
  WC_ORDERS: ["ID_ORDEN", "ESTADO", "CLIENTE", "TELEFONO", "DNI_CUIT", "DIRECCION_FACTURACION", "LOCALIDAD", "PROVINCIA", "CP", "RESUMEN_PRODUCTOS", "SUBTOTAL_PRODUCTOS", "COSTO_ENVIO", "METODO_ENVIO", "TIPO_ENVIO", "TOTAL_VENTA", "FECHA_PEDIDO", "NOTAS_ORDEN", "ULTIMA_ACTUALIZACION"],
  WC_DETAILS: ["ID_DETALLE", "ID_ORDEN", "SKU", "PRODUCTO", "CANTIDAD", "PRECIO_UNIT", "TOTAL_LINEA", "PRECIO_TIPO", "UNIDADES_PACK", "COLOR", "TALLE", "INVENTARIO_ID", "DESCRIPCION_VENTA"],
  BARTENDER_HISTORY: ["FECHA_PROCESADA", "FECHA_EJECUCION", "HORA_EJECUCION", "ORIGEN", "TIPO_EJECUCION"],
  CLIENT_FORM_LOG: ["LOG_ID", "CLIENTE_ID", "CORREO_ELECTRONICO", "GESTION", "FECHA_HORA"],
  TARIFARIO_GCP: ["SKU_ID", "SKU_DESC", "UNIDAD", "CANTIDAD_BASE", "PRECIO_LISTA", "ULTIMA_ACTUALIZACION"],
  LAB_IA: ["TIMESTAMP", "IMAGEN_ID", "SKU", "CATEGORIA", "ESTILO", "ANALISIS_FORENSE", "FORENSE_RAW", "PROMPT_MAESTRO", "PROMPT_RAW", "MODELO", "VERSION_REGLAS", "CONFIG_PARAMS", "COSTO"]
};
